/**
 * デモ用サンプルデータ
 *
 * APIキー未設定時に返すリアルなサンプルデータ。
 * 実際の市場価格を参考にした値を使用。
 */

/**
 * プリセットごとのデモデータを返す
 * @param {string} keyword - 検索キーワード
 * @returns {object|null}
 */
export function getDemoData(keyword) {
    const normalizedKeyword = keyword.toLowerCase();

    // キーワードに基づいてデモデータを選択
    for (const [key, data] of Object.entries(DEMO_DATASETS)) {
        if (normalizedKeyword.includes(key)) {
            return {
                ...data,
                keyword,
                searchedAt: new Date().toISOString(),
                isDemo: true,
            };
        }
    }

    // マッチしない場合は汎用デモ
    return {
        ...DEMO_DATASETS['generic'],
        keyword,
        searchedAt: new Date().toISOString(),
        isDemo: true,
    };
}

// ============================================================
//  デモデータセット
// ============================================================

const DEMO_DATASETS = {
    // 無印良品
    'muji': {
        rates: { usdToJpy: 149.5 },
        ebayStats: {
            count: 45,
            max: 8950,
            min: 1500,
            avg: 4200,
            median: 3800,
        },
        ebayTopItems: [
            {
                title: 'MUJI Aroma Diffuser Ultrasonic Large 250ml Japan NEW',
                priceJpy: 8950,
                priceOriginal: 'USD 59.90',
                imageUrl: '',
                url: 'https://www.ebay.com/itm/example1',
                condition: 'New',
                location: 'JP',
            },
            {
                title: 'MUJI Travel Neck Pillow Microbead Japan Made',
                priceJpy: 7470,
                priceOriginal: 'USD 49.99',
                imageUrl: '',
                url: 'https://www.ebay.com/itm/example2',
                condition: 'New',
                location: 'JP',
            },
            {
                title: 'MUJI Fountain Pen Aluminum Hexagonal Japan',
                priceJpy: 5980,
                priceOriginal: 'USD 39.99',
                imageUrl: '',
                url: 'https://www.ebay.com/itm/example3',
                condition: 'New',
                location: 'JP',
            },
            {
                title: 'MUJI Cotton Pad 189 Sheets UNBLEACHED Organic Japan',
                priceJpy: 2990,
                priceOriginal: 'USD 19.99',
                imageUrl: '',
                url: 'https://www.ebay.com/itm/example4',
                condition: 'New',
                location: 'JP',
            },
            {
                title: 'MUJI Gel Ink Pen 0.38mm 10 Color Set Japan',
                priceJpy: 4480,
                priceOriginal: 'USD 29.99',
                imageUrl: '',
                url: 'https://www.ebay.com/itm/example5',
                condition: 'New',
                location: 'JP',
            },
        ],
        opportunities: [
            {
                domesticTitle: '無印良品 超音波アロマディフューザー 大（加湿機能付）MJ-ADB1',
                domesticPrice: 4990,
                domesticUrl: 'https://www.rakuten.co.jp/example1',
                domesticImageUrl: '',
                domesticShop: '無印良品 楽天市場店',
                domesticReviewCount: 342,
                domesticReviewAvg: 4.5,
                ebayAvgPrice: 4200,
                ebayMedianPrice: 3800,
                ebayMaxPrice: 8950,
                ebayMinPrice: 1500,
                ebayListingCount: 45,
                estimatedSellPrice: 8950,
                ebayFee: 1164,
                paymentFee: 269,
                shippingCost: 2000,
                netProfit: 527,
                profitRate: 11,
                roi: 79,
                rates: { usdToJpy: 149.5 },
            },
            {
                domesticTitle: '無印良品 フィットするネッククッション 杢グレー',
                domesticPrice: 1990,
                domesticUrl: 'https://www.rakuten.co.jp/example2',
                domesticImageUrl: '',
                domesticShop: '無印良品 楽天市場店',
                domesticReviewCount: 891,
                domesticReviewAvg: 4.3,
                ebayAvgPrice: 4200,
                ebayMedianPrice: 3800,
                ebayMaxPrice: 7470,
                ebayMinPrice: 2990,
                ebayListingCount: 45,
                estimatedSellPrice: 7470,
                ebayFee: 971,
                paymentFee: 224,
                shippingCost: 2000,
                netProfit: 2285,
                profitRate: 115,
                roi: 275,
                rates: { usdToJpy: 149.5 },
            },
            {
                domesticTitle: '無印良品 アルミ丸軸万年筆',
                domesticPrice: 1090,
                domesticUrl: 'https://www.rakuten.co.jp/example3',
                domesticImageUrl: '',
                domesticShop: '無印良品 楽天市場店',
                domesticReviewCount: 156,
                domesticReviewAvg: 4.1,
                ebayAvgPrice: 4200,
                ebayMedianPrice: 3800,
                ebayMaxPrice: 5980,
                ebayMinPrice: 2990,
                ebayListingCount: 45,
                estimatedSellPrice: 5980,
                ebayFee: 777,
                paymentFee: 179,
                shippingCost: 1500,
                netProfit: 2434,
                profitRate: 223,
                roi: 449,
                rates: { usdToJpy: 149.5 },
            },
            {
                domesticTitle: '無印良品 ゲルインキボールペン 0.38mm 10色セット',
                domesticPrice: 880,
                domesticUrl: 'https://www.rakuten.co.jp/example4',
                domesticImageUrl: '',
                domesticShop: '無印良品 楽天市場店',
                domesticReviewCount: 2103,
                domesticReviewAvg: 4.7,
                ebayAvgPrice: 4200,
                ebayMedianPrice: 3800,
                ebayMaxPrice: 4480,
                ebayMinPrice: 1500,
                ebayListingCount: 45,
                estimatedSellPrice: 4480,
                ebayFee: 582,
                paymentFee: 134,
                shippingCost: 1500,
                netProfit: 1384,
                profitRate: 157,
                roi: 409,
                rates: { usdToJpy: 149.5 },
            },
            {
                domesticTitle: '無印良品 オーガニックコットンパフ 189枚入',
                domesticPrice: 399,
                domesticUrl: 'https://www.rakuten.co.jp/example5',
                domesticImageUrl: '',
                domesticShop: '無印良品 楽天市場店',
                domesticReviewCount: 567,
                domesticReviewAvg: 4.6,
                ebayAvgPrice: 4200,
                ebayMedianPrice: 3800,
                ebayMaxPrice: 2990,
                ebayMinPrice: 1500,
                ebayListingCount: 45,
                estimatedSellPrice: 2990,
                ebayFee: 389,
                paymentFee: 90,
                shippingCost: 1500,
                netProfit: 612,
                profitRate: 153,
                roi: 649,
                rates: { usdToJpy: 149.5 },
            },
        ],
        summary: {
            totalOpportunities: 5,
            profitableCount: 5,
            bestProfit: 2434,
            avgProfit: 1448,
        },
    },

    // マンガ初版
    'manga': {
        rates: { usdToJpy: 149.5 },
        ebayStats: {
            count: 32,
            max: 89700,
            min: 3000,
            avg: 22400,
            median: 15000,
        },
        ebayTopItems: [
            {
                title: 'ONE PIECE Vol.1 First Edition Print Japanese Manga 1997',
                priceJpy: 89700,
                priceOriginal: 'USD 599.99',
                imageUrl: '',
                url: 'https://www.ebay.com/itm/manga1',
                condition: 'Used',
                location: 'JP',
            },
            {
                title: 'Dragon Ball Vol.1 First Print Japanese Manga Toriyama',
                priceJpy: 67275,
                priceOriginal: 'USD 449.99',
                imageUrl: '',
                url: 'https://www.ebay.com/itm/manga2',
                condition: 'Used',
                location: 'JP',
            },
            {
                title: 'Naruto Vol.1 First Edition Japanese Manga Kishimoto',
                priceJpy: 37375,
                priceOriginal: 'USD 249.99',
                imageUrl: '',
                url: 'https://www.ebay.com/itm/manga3',
                condition: 'Used',
                location: 'JP',
            },
            {
                title: 'Demon Slayer Vol.1 First Print Japanese Manga',
                priceJpy: 29900,
                priceOriginal: 'USD 199.99',
                imageUrl: '',
                url: 'https://www.ebay.com/itm/manga4',
                condition: 'Used',
                location: 'JP',
            },
            {
                title: 'Attack on Titan Vol.1 First Edition Japanese',
                priceJpy: 14950,
                priceOriginal: 'USD 99.99',
                imageUrl: '',
                url: 'https://www.ebay.com/itm/manga5',
                condition: 'Used',
                location: 'JP',
            },
        ],
        opportunities: [
            {
                domesticTitle: 'ONE PIECE 1巻 初版 尾田栄一郎 集英社',
                domesticPrice: 15000,
                domesticUrl: 'https://www.rakuten.co.jp/manga1',
                domesticImageUrl: '',
                domesticShop: 'ブックオフオンライン楽天市場店',
                domesticReviewCount: 0,
                domesticReviewAvg: 0,
                ebayAvgPrice: 22400,
                ebayMedianPrice: 15000,
                ebayMaxPrice: 89700,
                ebayMinPrice: 3000,
                ebayListingCount: 32,
                estimatedSellPrice: 89700,
                ebayFee: 11661,
                paymentFee: 2691,
                shippingCost: 1500,
                netProfit: 58848,
                profitRate: 392,
                roi: 498,
                rates: { usdToJpy: 149.5 },
            },
            {
                domesticTitle: 'ドラゴンボール 1巻 初版 鳥山明 集英社',
                domesticPrice: 12000,
                domesticUrl: 'https://www.rakuten.co.jp/manga2',
                domesticImageUrl: '',
                domesticShop: '古本市場オンライン楽天店',
                domesticReviewCount: 0,
                domesticReviewAvg: 0,
                ebayAvgPrice: 22400,
                ebayMedianPrice: 15000,
                ebayMaxPrice: 67275,
                ebayMinPrice: 3000,
                ebayListingCount: 32,
                estimatedSellPrice: 67275,
                ebayFee: 8746,
                paymentFee: 2018,
                shippingCost: 1500,
                netProfit: 43011,
                profitRate: 358,
                roi: 461,
                rates: { usdToJpy: 149.5 },
            },
            {
                domesticTitle: 'NARUTO 1巻 初版 岸本斉史 集英社',
                domesticPrice: 5000,
                domesticUrl: 'https://www.rakuten.co.jp/manga3',
                domesticImageUrl: '',
                domesticShop: 'ネットオフ楽天市場支店',
                domesticReviewCount: 0,
                domesticReviewAvg: 0,
                ebayAvgPrice: 22400,
                ebayMedianPrice: 15000,
                ebayMaxPrice: 37375,
                ebayMinPrice: 3000,
                ebayListingCount: 32,
                estimatedSellPrice: 37375,
                ebayFee: 4859,
                paymentFee: 1121,
                shippingCost: 1500,
                netProfit: 24895,
                profitRate: 498,
                roi: 648,
                rates: { usdToJpy: 149.5 },
            },
        ],
        summary: {
            totalOpportunities: 3,
            profitableCount: 3,
            bestProfit: 58848,
            avgProfit: 42251,
        },
    },

    // 汎用デモ
    'generic': {
        rates: { usdToJpy: 149.5 },
        ebayStats: {
            count: 25,
            max: 14950,
            min: 1500,
            avg: 5980,
            median: 4480,
        },
        ebayTopItems: [
            {
                title: 'Japanese Product - Premium Quality Import',
                priceJpy: 14950,
                priceOriginal: 'USD 99.99',
                imageUrl: '',
                url: 'https://www.ebay.com/itm/generic1',
                condition: 'New',
                location: 'JP',
            },
            {
                title: 'Japan Exclusive Item - Limited Edition',
                priceJpy: 7475,
                priceOriginal: 'USD 49.99',
                imageUrl: '',
                url: 'https://www.ebay.com/itm/generic2',
                condition: 'New',
                location: 'JP',
            },
            {
                title: 'Made in Japan - High Quality Product',
                priceJpy: 4480,
                priceOriginal: 'USD 29.99',
                imageUrl: '',
                url: 'https://www.ebay.com/itm/generic3',
                condition: 'New',
                location: 'JP',
            },
        ],
        opportunities: [
            {
                domesticTitle: '日本製プレミアム商品（デモ）',
                domesticPrice: 3980,
                domesticUrl: 'https://www.rakuten.co.jp/generic1',
                domesticImageUrl: '',
                domesticShop: 'デモショップ',
                domesticReviewCount: 100,
                domesticReviewAvg: 4.2,
                ebayAvgPrice: 5980,
                ebayMedianPrice: 4480,
                ebayMaxPrice: 14950,
                ebayMinPrice: 1500,
                ebayListingCount: 25,
                estimatedSellPrice: 4480,
                ebayFee: 582,
                paymentFee: 134,
                shippingCost: 2000,
                netProfit: -216,
                profitRate: -5,
                roi: 13,
                rates: { usdToJpy: 149.5 },
            },
        ],
        summary: {
            totalOpportunities: 1,
            profitableCount: 0,
            bestProfit: -216,
            avgProfit: -216,
        },
    },
};
